Models/Catagory.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia3.Models
{
    public class Catagory
    { 
        public int Id { get; set; }
        [Required(ErrorMessage ="Duzgun doldur!")]
        public string Name { get; set; }
      public  List<Product>? Products { get; set; }
    }
}

Models/Product.cs
namespace Pronia3.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int CatagoryId { get; set; } 
        public Catagory Catagory { get; set;}
      public  List <ProductPhoto> ProductPhotos { get; set; }
      public  List<Tag> Tags { get; set; }
    }
}

Models/ProductPhoto.cs
using System.Data.SqlTypes;

namespace Pronia3.Models
{
    public class ProductPhoto
    {
        public int Id { get; set; }
        public string PhotoUrl { get; set; }
        public bool IsMain { get; set;}
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

Models/Slider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pronia3.Models
{
	public class Slider
	{
		public int Id { get; set; }
		[Required(ErrorMessage ="Duzgun daxil edin")]
		public string Title { get; set; }
		[StringLength(30,ErrorMessage ="Uzunlugu Duzgun Daxil edin")]
		public string SubTitle { get; set; }
		public string Description { get; set; }
		public string? ImgUrl { get; set; }

		[NotMapped]
		public IFormFile PhotoFile { get; set; }
	}
}

Models/Tag.cs
namespace Pronia3.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        List<Product> Products{ get; set; }    
    }
}

Areas/Admin/Controllers/CatagoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia3.DAL;
using Pronia3.Models;

namespace Pronia3.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CatagoryController : Controller
    {
        AppDbContext _context;

        public CatagoryController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Catagory> catagories = _context.Catagories.Include(x => x.Products).ToList();

            return View(catagories);
        }


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Catagory catagory)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            _context.Catagories.Add(catagory);
                _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var catagory=_context.Catagories.FirstOrDefault(x=>x.Id==id);
            if (catagory == null)
            {
                return RedirectToAction("Index");
            }
            return View(catagory);
        }

        [HttpPost]
        public IActionResult Update(Catagory newcatagory)
		{
			var oldcatagory = _context.Catagories.FirstOrDefault(x => x.Id == newcatagory.Id);
			if (oldcatagory == null)
			{
				return RedirectToAction("Index");
			}

            if (!ModelState.IsValid)
            {
                return View();
            }
            oldcatagory.Name = newcatagory.Name;
            _context.SaveChanges();
			return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int? id)
        {
            var catagory=_context.Catagories.FirstOrDefault(x => x.Id == id);
            _context.Catagories.Remove(catagory);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pronia3.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
       
        public IActionResult Index()
        {

            return View();
        }
    }
}

Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Pronia3.DAL;
using Pronia3.Models;
using System.Reflection.Metadata;

namespace Pronia3.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class SliderController : Controller
	{
		AppDbContext _context;
		IWebHostEnvironment _environment;

        public SliderController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }


        public IActionResult Index()
		{

			List<Slider> sliders = _context.Sliders.ToList();
			return View(sliders);
		}

		public IActionResult Create()
		{


			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(Slider slider)
		{
			if (!slider.PhotoFile.ContentType.Contains("image/"))
		    {
                ModelState.AddModelError("PhotoFile","Formati duzgunn daxil edin");
				return View();

			}
			

			string filename = slider.PhotoFile.FileName;
			string path = _environment.WebRootPath + @"\Upload\Slider\" + filename;

            using (FileStream fileStream = new(path, FileMode.Create))
			{
				slider.PhotoFile.CopyTo(fileStream);

			}
			slider.ImgUrl = filename;

			if(!ModelState.IsValid)
            {
				return View();
			}
			await _context.Sliders.AddAsync(slider);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		 public IActionResult Update(int id)
		{
			return View(_context.Sliders.Find(id));
		}
		public IActionResult Delete(int id)
		{
			
			var slider = _context.Sliders.FirstOrDefault(x => x.Id == id);
			string path = _environment.WebRootPath + @"\Upload\Slider" + slider.ImgUrl;
			FileInfo fileInfo = new FileInfo(path);
			if(fileInfo.Exists)
			{
				fileInfo.Delete();
			}
            _context.Sliders.Remove(slider);
			_context.SaveChanges();
			return RedirectToAction(nameof(Index));


        }
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia3.DAL;
using Pronia3.Models;
using Pronia3.ViewModel;
using System.Diagnostics;

namespace Pronia3.Controllers
{
    public class HomeController : Controller
    {

        AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            List<Product> products = _context.Products.Include(x => x.ProductPhotos).Where(x => x.ProductPhotos.Count > 0).ToList();

            HomeVM homeVM = new HomeVM()
            {
                Products = products,
                Sliders = _context.Sliders.ToList()
            };


            return View(homeVM);

        }
           

        
      
        public IActionResult Detail(int? id)
        {
            return View();
        }
       
    }
}

Areas/Admin/Views/Catagory/Create.cshtml
@model Catagory


<div class="container">
<form  method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" >
        <span asp-validation-for="Name" style="color:red"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

Areas/Admin/Views/Catagory/Index.cshtml
@using Pronia3.Models
@model List<Catagory>
@{
    int count = 0;
}
<h1>Catagories
    <a class="btn btn-primary" asp-action="Create" >Create</a>
</h1>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">ProductCount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Products.Count()</td>
                    <td><a class="btn btn-warning" asp-action="Update" asp-controller="Catagory" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Catagory" asp-route-id="@item.Id">Delete</a> </td>
                    
                </tr>

            }
        </tbody>
    </table>
</div>

Areas/Admin/Views/Catagory/Update.cshtml
@model Catagory


<div class="container">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Areas/Admin/Views/Slider/Create.cshtml
@model Slider

<div class="container">
<form method="post" enctype="multipart/form-data">
       <div class="row" >
            <div class="mb-3 col-md-4">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="SubTitle" class="form-label">SubTitle</label>
                <input asp-for="SubTitle" class="form-control">
                <span asp-validation-for="SubTitle" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
                <input asp-for="PhotoFile" class="form-control">
                <span asp-validation-for="PhotoFile" style="color:red"></span>
            </div>
       </div>
       
       <div class="row">
            <div class="mb-3 col-md-8" >
                <label for="Description" class="form-label">Description</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
                <span asp-validation-for="Description" style="color:red"></span>
            </div>
       </div>
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

Areas/Admin/Views/Slider/Index.cshtml
@using Pronia3.Models
@model List<Slider>
@{
    int count = 0;
}
<h1>
    Sliders
    <a class="btn btn-primary" asp-action="Create">Create</a>
</h1>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">SubTitle</th>
                <th scope="col">Decription</th>
                <th scope="col">Images</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.Title</td>
                    <td>@item.SubTitle</td>
                    <td>@item.Description</td>
                    <td>
                        <div style="width:100px">
                            <img width="100%" src="~/Upload/Slider/@item.ImgUrl">
                    </div>
                    </td>
                    <td>
                        <a class="btn btn-warning" asp-action="Update" asp-controller="Slider" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Slider" asp-route-id="@item.Id">Delete</a>
                    </td>

                </tr>

            }
        </tbody>
    </table>
</div>

Areas/Admin/Views/Slider/Update.cshtml
@model Slider
<div class="container">
    <form method="post">
        <div class="row">
            <div class="mb-3 col-md-4">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="SubTitle" class="form-label">SubTitle</label>
                <input asp-for="SubTitle" class="form-control">
                <span asp-validation-for="SubTitle" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
                <input asp-for="PhotoFile" class="form-control">
                <span asp-validation-for="PhotoFile" style="color:red"></span>
            </div>
        </div>

        <div class="row">
            <div class="mb-3 col-md-8">
                <label for="Description" class="form-label">Description</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
                <span asp-validation-for="Description" style="color:red"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>